import Proofs.Lang
import Mathlib.Tactic.DeriveFintype
import Proofs.CFG
open Lang

variable {Sigma : Type}[Alphabet Sigma]

/-

Components of a compiler:
            |    Seen this section in haskell   |
  Program → Parser → Syntax Tree → Code Generator → Code
            ^^^^^^
            Just a CFG

How do we write a parser?
  Needs to be un-ambiguous


-/

open Cfg
open Sum

variable (G : CFG Sigma)

inductive SigmaA : Type
| lpar | rpar | a | plus | times
deriving Fintype, DecidableEq
open SigmaA

namespace Ga
inductive NTA : Type
| E | T | F
deriving Fintype, DecidableEq
open NTA

abbrev GA : CFG SigmaA :=
{ NT := NTA
  S := E
  P := { (E, [inl T]),
         (E , [inl E,inr plus,inl T]),
         (T, [inl F]),
         (T , [inl T,inr times,inl F]),
         (F, [inr SigmaA.a]),
         (F, [inr lpar,inl E,inr rpar])}
   }

end Ga


/-
example translating the language:
  S → aSa | bSb | ε
into a CFG:
-/

namespace Ex
inductive SigmaAB : Type where
| a | b
deriving Fintype, DecidableEq

open SigmaAB

abbrev GG : CFG SigmaAB :=
{
  NT := Fin 1
  S := (0 : Fin 1)
  P := { (0  , [inr (SigmaAB.a), inl (0 : Fin 1), inr (SigmaAB.a)] ),
         (0  , [inr (SigmaAB.b), inl (0 : Fin 1), inr (SigmaAB.b)] ),
         (0 , [])}
}

/- What is the language for this grammar?

just any even length palindromes as it builds the word from the inside out

-/


/-
**Why do we need deterministic CFGs for compiler design?**

If the CFG representing the language is non-deterministic
then it means we need to store all possible execution traces
so that then we can make sure that if there is a branch that exists
then the system is going to find it
however say we have 3 states,
  and each on of those states maps to 3 states,
  and each on of those states maps to 3 states and so on ...

then by the time we get to accepting states,
the size and complexity of the parse trace is going to be
way to large to be feasible,
hence we need to make CFGs deterministic so we dont get massive
memory usage


**TLDR**
Needs CFGs to be deterministic so that the parser defined
over them doesn't become incredibly time and space complex
as a result of tracking all possible execution traces
-/

/-
Complexity of the parser
  We want this to be linear

However while CFGs are decidable in general
  the algos to do this is are O(n³)

So we want to make the deterministic so that compilers become more efficient,
this is where the LL(1) category comes in:

  L → Left-to-Right scanning
        Means the parser reads your code
        from left to right

  L → Leftmost Derivation
        When the grammar expands a rule,
        it then further expands starting with the leftmost non-terminal first

        ie:
          S → ABC
          Then we would evalute A first before moving on to B & C

  (1) → 1 symbol of lookahead

-/

-- Formal conditions for a grammar to be LL(1)
/-
defining all the characters that can possibly appear
at the start of a word generated by the non-terminal α
  defined as sentenial form as it can be terminal or non-terminal

used so a parser can instantly know what values it can/cant accept
-/
abbrev First (α : Sent G) : Set Sigma
:= { a | ∃ β, DerivStar G (α , a :: β )}


abbrev Follow (A : G.NT) : Set (Option Sigma)
:= {x | ∃ α β a, x = some a ∧ DerivStar G ([inl G.S], α++[inl A, inr a]++β)}
    ∪ {none | ∃ α , DerivStar G ([inl G.S] , α++[inl A])}

/-
defines the follow set for a given Non-Terminal

So for the given current non-terminal,
what is the set of terminal characters allowed to follow
as defined by the grammar of the system


  (before ∪)
defines the case that this non-terminal isn't the last character

  (after ∪)
defines the case that this non-terminal is the last character

-/




/-
LA → Look Ahead
Basically a wrapper for First
but allows epsilon to be used as we have Option Sigma input type
-/
abbrev LA (A : G.NT)( α : Sent G) : Set (Option Sigma)
:={some x | x ∈ First G α} ∪ {x | x ∈ Follow G A ∧ α = []}

abbrev isLL1 :=
  ∀ A, ∀ α β , (A , α ) ∈ G.P ∧ (A, β) ∈ G.P ∧ α ≠ β → LA G A α ∩ LA G A β = {}
  /-
  For all non-terminal variable A in our grammar
  and for any two potential right hand sides α β

  If the rule
    A → α
    A → β
      Note α & β reprsent the full output string (ie z W q)
  are both in our grammar's production list

  and α ≠ β
  then that implies the intersection of their lookahead sets
  must be empty

  in normal terms
    Rule α = A → x Y z
    Rule β = A → x W v

    so we're in the current state A and want to see which route to take

    so we look at the outputs from all the production rules from A:
      A → x Y z
      A → x W v

    and because this is an LL(1) we have a look ahead of 1
      which means we can see the first character of each output from each production rule from A:

      → (x) Y z
      → (x) W v

    but this means all our parser (cfg) sees is:
      A → x
      A → x

    so it can't figure out which trace to take

  for example:
    A → Bc (α rule)
    A → dB (β rule)
    B → d
    B → x

    so our FIRST (LA) sets are:
      LA(α) = {d, x} - from following NT through the productions
      LA(β) = {d}

    so now even though α ≠ β it means LA(α) ∩ LA(β) = {d}
      which means that the parser wouldn't know whether to use
      rule α or rule β
      and hence our CFG is not LL(1)
  -/



end Ex
